language: node_js
sudo: false
node_js:
- 'node'
deploy:
- provider: npm
  email: robertknight@gmail.com
  api_key:
    secure: e5FFL8+lzUkrNnwjdiNAkzf/I8PIof6K9oPHljHVkqFtERFU80ffQqQvB7UK4Mo2L58HJAg9zyvaLqqHN049AFQxolLo6Z3Bx2n8iGuEDnG00FpBhA1ArbRhNWQN/7EH+Lo1xeABhTDb6ub11mxl10pxcPbJYuwCmkQ9jPYYRPQ=
  skip_cleanup: true
